# Generated by Django 5.1.3 on 2024-11-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
