# Generated by Django 5.1.3 on 2024-11-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('mail', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('phone', models.IntegerField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('mail', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('phone', models.IntegerField(default='', unique=True)),
            ],
        ),
    ]
